name: student_management_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'  # Adjust according to your Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3  # Use a stable version of hive
  hive_flutter: ^1.1.0 
  path_provider: ^2.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.0
  uuid: ^3.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0  # Match this with hive version
  build_runner: ^2.4.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true